spring.application.name=LearningPlatformValidation

# Server Configuration
server.port=8080

# Configuration Oracle Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Congiguration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Configurcion Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
# management.endpoint.env.show-values=ALWAYS

# Configuracion Actuator/info
info.app.name=Microservicio de Cursos LearningPlatform
info.app.description=Este microservicio del Backend gestiona los cursos de la plataforma con SpringBoot y H2.
info.app.version=2.0.0

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.duoc=DEBUG