spring.application.name=${APP_NAME}

# Server Configuration
server.port=${SERVER_PORT}

# Configuration Oracle Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS}

# Congiguration JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
spring.jpa.database-platform=${JPA_DIALECT}

# Configurcion Actuator
management.endpoints.web.exposure.include=${ACTUATOR_EXPOSE}
management.info.env.enabled=${ACTUATOR_INFO_ENV}
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
# management.endpoint.env.show-values=ALWAYS

# Configuracion Actuator/info
info.app.name=${INFO_APP_NAME}
info.app.description=${INFO_APP_DESCRIPTION}
info.app.version=${INFO_APP_VERSION}

logging.level.org.hibernate.SQL=${LOG_HIBERNATE_SQL}
logging.level.org.springframework.web=${LOG_SPRING_WEB}

# Logging Configuration
logging.level.org.springframework=${LOG_SPRING}
logging.level.com.duoc=${LOG_COM_DUOC}